spring.application.name=capstone
spring.config.import=file:env.properties
## SERVER ##
server.port=${SERVER_PORT}
server.address=${SERVER_ADDRESS}
## DATABASE ##
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
## HIBERNATE ##
spring.jpa.hibernate.ddl-auto=update
## JWT ##
jwt.secret=${JWT_SECRET}
## ORIGINS ##
localhost.port=${LOCALHOST_PORT}
frontend.url=http://localhost:${localhost.port}
## CLOUDINARY ##
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.apikey=${CLOUDINARY_API_KEY}
cloudinary.secret=${CLOUDINARY_API_SECRET}
## SERVLET ##
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
## GOOGLE API ##
google.apiKey=${GOOGLE_API_KEY}
# MAILGUN
mailgun.domainName=${MAILGUN_DOMAIN_NAME}
mailgun.apiKey=${MAILGUN_API_KEY}